version: '3.0'
services:
  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
  rtsp:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
    volumes:
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml
  api:
    build: 
      context: ./express-api
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_STREAMING=stream.jiewen.wang
  streamer:
    build:
      context: ./libav-RTMP-Streaming
    volumes:
      - ./libav-RTMP-Streaming:/files
