version: '3.0'
services:
  #rtmp:
  #  image: https://github.com/tiangolo/nginx-rtmp-docker.git
  api:
    build: 
      context: ./express-api
    ports:
      - "81:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_STREAMING=stream.jiewen.wang
  streamer:
    build:
      context: ./libav-RTMP-Streaming
    image: streamer:latest
    volumes:
      - ./libav-RTMP-Streaming:/files
